export SPARK_HOME=~/local/spark
export PATH=$SPARK_HOME/bin:$PATH
export PYTHON_PATH=$SPARK_HOME/python
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
export PYSPARK_PYTHON=python3